[tool.poetry]
name = "mondot_shell"
version = "2.0.0"
description = "Shell for Mondot GUI"
authors = ["thiagola92 <thiagola92@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "mondot", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.11.3,<3.12"
pyinstaller = "^5.12.0"
pymongo = {extras = ["srv"], version = "^4.3.3"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
