[tool.pdm]

[project]
name = "mondot_shell"
version = "2.0.0"
description = "Shell for Mondot GUI"
authors = [
    {name = "thiagola92", email = "thiagola92@gmail.com"},
]
dependencies = [
    "pymongo>=4.3.3",
    "pyinstaller>=5.11.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}