on:
  workflow_dispatch

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11.0"
      - run: pdm install
      - run: pdm run unittest
      - run: pdm run build
      - run: zip dist/shell.zip dist/shell
      - uses: actions/upload-artifact@v3
        with:
          name: shell-linux
          path: dist/shell.zip
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11.0"
      - run: pdm install
      - run: pdm run unittest
      - run: pdm run build
      - run: zip dist/shell.zip dist/shell
      - uses: actions/upload-artifact@v3
        with:
          name: shell-macos
          path: dist/shell.zip
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11.0"
      - run: pdm install
      - run: pdm run unittest
      - run: pdm run build
      - run: tar -a -c -f dist/shell.zip dist/shell.exe
      - uses: actions/upload-artifact@v3
        with:
          name: shell-windows
          path: dist/shell.zip
        