on:
  workflow_call:

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11.0"
      - run: pdm install
      - run: pdm run black
      - run: pdm run isort
      - run: pdm run unittest
      - uses: EndBug/add-and-commit@v9
        with:
          message: Format code
          default_author: github_actions