name: python-unittest

on:
  push:
    branches: [ main ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run unittest
        run: python -m unittest discover -v -s tests -p *_test.py